      subroutine TCAL(I,IFLG)
      PARAMETER (ML=30)
      IMPLICIT REAL*8 (A-H,O-Z)
      integer*4 ntwissfun
      parameter (ntwissfun=20)
      COMMON /TWISSP/TWPIN(ntwissfun),TWPOT(ntwissfun),
     +   AU,BU,PU,AV,BV,PV,EU,EPU,EV,EPV,R1,R2,R3,R4,DU,DUP,DV,DVP
      COMMON /TMATR/TM(4,4),VM(4),TO(4,4),VO(4),TU(4,4),VU(4)
      COMMON /ELEM/ANG,E1,E2,TETA,RLE,RKL1,RKL2
      COMMON /DELEM/DL,DKL0,DKL1,DKL2,CKL0X,CKL0Y,CKL1X,CKL1Y
      COMMON /FUNS/FUNI(ML,15)
      DIMENSION R0(4,4),R0I(4,4)
      IF(DL.EQ.0.) WRITE(6,'(A)') '  DL=0. IN TCAL '
      RK1=CKL1X/DL
      CURV=DSQRT(CKL0X*CKL0X+CKL0Y*CKL0Y)/DL
      GU=(1+AU*AU)/BU
      GV=(1+AV*AV)/BV
      IF(I.EQ.1) CALL R0CAL(R0,R0I)
      CURV2=CURV*CURV
      CURV3=CURV2*DABS(CURV)
      FUNI(I,1)=CKL0X*
     +          (R0I(1,1)*EU+R0I(1,2)*EPU+R0I(1,3)*EV+R0I(1,4)*EPV)
      FUNI(I,2)=CURV2*DL
      FUNI(I,3)=CURV3*DL
      IF(CURV.GT.0) THEN
      FUNI(I,4)=(CKL0X+2*CKL1X/CURV)*CURV2*(R0I(1,1)*EU+R0I(1,2)*EPU)
     +         +(CKL0Y-2*CKL1Y/CURV)*CURV2*(R0I(3,1)*EU+R0I(3,2)*EPU)
      ELSE
      FUNI(I,4)=0.
      END IF
      FUNI(I,5)=CURV3*(GU*EU*EU+2.*AU*EPU*EU+BU*EPU*EPU)*DL
* 6: I1Y    7:I4Y     8:I5Y
      FUNI(I,6)=CKL0Y*
     +          (R0I(3,1)*EU+R0I(3,2)*EPU+R0I(3,3)*EV+R0I(3,4)*EPV)
      IF(CURV.GT.0) THEN
      FUNI(I,7)=(CKL0X+2*CKL1X/CURV)*CURV2*(R0I(1,3)*EV+R0I(1,4)*EPV)
     +         +(CKL0Y-2*CKL1Y/CURV)*CURV2*(R0I(3,3)*EV+R0I(3,4)*EPV)
      ELSE
      FUNI(I,7)=0.
      END IF
      FUNI(I,8)=CURV3*(GV*EV*EV+2.*AV*EPV*EV+BV*EPV*EPV)*DL
* 9:  CHROMX   10: CHROMY
      FUNI(I,9)=(RK1+CURV2)*BU*DL
      FUNI(I,10)=-RK1*BV*DL
      FUNI(I,11)=CKL0X
      FUNI(I,12)=CKL0Y
      IF(IFLG.EQ.1) RETURN
      CALL TMATRS(R0,R0I)
      CALL TWTRANS(R0,R0I)
      END
