      subroutine SEXTU(TETA,DX,DY)
      IMPLICIT REAL*8 (A-H,O-Z)
      COMMON /DELEM/DL,DKL0,DKL1,DKL2,CKL0X,CKL0Y,CKL1X,CKL1Y
      CALL UNITM4(TM,1.)
      CALL UNITM4(TO,1.)
      CALL ZEROV4(VM)
      CALL ZEROV4(VO)
      SINT=DSIN(3.*TETA)
      COST=DCOS(3.*TETA)
      CKL0Y=-DKL2*(DX*DY*COST           +(DX*DX-DY*DY)/2.*SINT)
      CKL0X=DKL2*((DX*DX-DY*DY)/2.*COST-DX*DY*SINT)
*     CKL1X=DKL2*(2.*(DX-DY)*COST-2.*DX*SINT)
*     CKL1Y=-CKL1X
        CKL1X=DKL2*DX
        CKL1Y=-DKL2*DY
      RETURN
      END
